# Project settings:
language: ruby
rvm:
  - "2.5.0"

# CI process:
script: bundle exec rspec spec

# Notification settings:
notifications:
  webhooks: https://eetnu.slack.com/services/hooks/travis?token=YC3xwKe1gu65ikh1XOaLrUEh
  campfire:
    on_success: change
    on_failure: always
    rooms:
      - "eetnu:bb17e8d4e843938b4b32ee4c1809f2f90b8456ae@316993"
